apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
      - name: loan-service
        image: your-dockerhub-username/loan-service:latest
        ports:
        - containerPort: 5002
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: service-secrets
              key: database_url
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: user_service_url
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: loan-service
spec:
  type: ClusterIP
  selector:
    app: loan-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002