name: Collection Service CI

on:
  push:
    paths:
      - 'collection-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('collection-service/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r collection-service/requirements.txt pytest requests-mock

    - name: Run unit tests
      run: pytest collection-service/tests/unit

    - name: Run integration tests (requires mocking)
      run: pytest collection-service/tests/integration

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and tag Docker image
      run: docker build -t your-dockerhub-username/collection-service:latest ./collection-service

    - name: Push Docker image
      run: docker push your-dockerhub-username/collection-service:latest