name: Reporting Service CI

on:
  push:
    paths:
      - 'reporting-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('reporting-service/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r reporting-service/requirements.txt
        pip install pytest requests-mock  # Ensure testing dependencies are installed

    - name: Run unit tests
      run: |
        cd reporting-service
        pytest tests/unit

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd reporting-service
        docker build -t your-dockerhub-username/reporting-service:latest .
        docker push your-dockerhub-username/reporting-service:latest